name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
   contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  codecov:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

    - name: Gen shared lib
      run: make
    - name: Run Tests
      run: make test

    - name: Upload Artifact
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882  # v4.4.3
      with:
        name: libspecfun+test-output
        path: |
          libspecfun.so
          specfun.test.txt
